---
- name: Config drift remediation listener
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001
  rules:
    - name: Catch all events (debug)
      condition: event is defined
      action:
        debug:
          msg: "Event received: {{ event }}"
