---
- name: Validate sshd config before reload
  ansible.builtin.command: /usr/sbin/sshd -t
  changed_when: false
  listen: "Restart sshd"

- name: Reload sshd
  ansible.builtin.service:
    name: sshd
    state: reloaded
  listen: "Restart sshd"
